export type InquiryRecord = {
  id: string;
  referenceId: string | null;
  type: string;
  name: string;
  email: string | null;
  phone: string | null;
  message: string | null;
  department: string | null;
  preferredDate: string | null;
  preferredTime: string | null;
  country: string | null;
  medicalCondition: string | null;
  address: string | null;
  resumeUrl: string | null;
  jobSlug: string | null;
  jobTitle: string | null;
  interviewDate: string | null;
  interviewTime: string | null;
  interviewInterviewer: string | null;
  interviewMode: "online" | "offline" | null;
  status: string;
  createdAt: string;
};
